server {
    listen 80;
    server_name projetocerradoifg.org www.projetocerradoifg.org guia.projetocerradoifg.org www.guia.projetocerradoifg.org;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# após rodar: sudo certbot --nginx -d projetocerradoifg.org -d www.projetocerradoifg.org -d guia.projetocerradoifg.org -d www.guia.projetocerradoifg.org
